version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: webapi/Dockerfile
    depends_on:
          - db  

  db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        ports:
          - "1433:1433"
        volumes:
          - ./data:/var/opt/mssql/data
          - ./log:/var/opt/mssql/log
          - ./secrets:/var/opt/mssql/secrets

        environment:
            SA_PASSWORD: "!!qwErty321!.!"
            ACCEPT_EULA: "Y"

  client:
    image: client
    build:
     context: ./vueapp
     dockerfile: Dockerfile

     

  proxy:
    image: nginx:mainline

       


