version: '3.4'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"


  client:
    ports:
    - "5002:8080"

  proxy:
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "80:80"  